services:
  app: 
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todoDB
    depends_on:
      - db  

  db: 
    image: postgres:13
    environment:
      POSTGRES_DB: todoDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"                                                    